window.SALES_DATA = {
  brand: "Noquinoli",
  currency: {
    locale: "es-AR",
    code: "ARS",
    decimals: 2,
    symbol: "$",
  },
  heroText: "Pasta artesanal, sabores de siempre. Pedidos por WhatsApp con entrega a domicilio.",
  tagLine: "PASTA ARTESANAL | ENTREGA A DOMICILIO",
  heroTitle: "El sabor de siempre, en tu puerta",
  mainCtaText: "Ver catalogo",
  sectionTitle: "Nuestro menu",
  sectionSubtitle: "Pasta artesanal, salsas caseras y pedidos directos por WhatsApp.",
  contact: {
    whatsapp: "5491112345678",
    footerMessage: "Pedidos por WhatsApp de martes a domingo, 12:00 a 15:00 y 19:00 a 23:00.",
  },
  activeCatalogId: "pastas",
  theme: {
    accent: "#dd1c23",
    accentDark: "#b5161d",
    deep: "#154729",
    bg: "#f7ebdc",
    card: "#fffdf7",
    ink: "#1f1f1f",
    ok: "#00ce8b",
  },
  catalogs: [
    {
      id: "pastas",
      name: "Pastas",
      products: [
        {
          name: "Noquis al pomodoro",
          price: 2800,
          image: "assets/images/noquis_congelados.webp",
          details: [
            "Noquis de papa artesanales",
            "Salsa pomodoro casera",
            "Porciones para 2 personas",
          ],
          ctaText: "Pedir ahora",
          defaultAction: "comprar",
          productStatus: "activo",
        },
      ],
    },
    {
      id: "salsas",
      name: "Salsas",
      products: [
        {
          name: "Salsa Bolognesa",
          price: 1500,
          image: "",
          details: [
            "Carne vacuna 100%",
            "Coccion lenta 4 horas",
            "Rinde para 4 porciones",
          ],
          ctaText: "Agregar al pedido",
          defaultAction: "comprar",
          productStatus: "activo",
        },
      ],
    },
  ],
  whatsappGroups: [
    {
      id: "grupo-gozc9",
      name: "Pedidos-SAGUAPAC",
      link: "https://chat.whatsapp.com/JkTCUfm42DK6CTo5w5GayL?mode=gi_t",
      days: ["lunes","martes","miercoles","jueves","viernes","sabado","domingo"],
      description: "Solicita código para ingresar",
      accessCode: "5555",
    },
    {
      id: "grupo-8q6e9",
      name: "Pedido sábado",
      link: "https://chat.whatsapp.com/JkTCUfm42DK6CTo5w5GayL?mode=gi_t",
      days: ["sabado"],
      description: "Grupo público para pedidos de sábado.",
      accessCode: "",
    },
    {
      id: "grupo-mgjm1",
      name: "Pedido grupos",
      link: "https://chat.whatsapp.com/JkTCUfm42DK6CTo5w5GayL?mode=gi_t",
      days: ["lunes","martes","miercoles","jueves","viernes","sabado","domingo"],
      description: "Grupo disponible para pedidos en cualquier día.",
      accessCode: "",
    },
  ],
};